In [1]:
import numpy as np

In [402]:
a = np.array([[1],[3],[5],[7]])

In [403]:
a = np.hstack([a ** (i+1) for i in range(2)])
a

array([[ 1,  1],
       [ 3,  9],
       [ 5, 25],
       [ 7, 49]])

In [404]:
y = np.array([[10],[20],[30],[40]])

In [405]:
meanfeature = np.mean(a, axis=0)
b=a-meanfeature

In [406]:
b

array([[ -3., -20.],
       [ -1., -12.],
       [  1.,   4.],
       [  3.,  28.]])

In [407]:
b= np.hstack([np.ones((len(b),1)), b])

In [410]:
w = np.linalg.inv(b.T @ b) @ b.T @ y

In [413]:
w

array([[25.],
       [ 5.],
       [ 0.]])

In [411]:
yh = np.matmul(b, w)

In [412]:
yh

array([[10.],
       [20.],
       [30.],
       [40.]])