In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

/Users/zhengyuzhang/miniconda3/envs/cse446/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
a=torch.randn(3, 2)

In [5]:
nn.Parameter(a)

Parameter containing:
tensor([[ 2.8403,  0.5356],
        [ 2.6108, -1.5940],
        [ 0.2943,  0.1081]], requires_grad=True)

In [11]:
b = torch.tensor([1, 2, 3, 0 , -1])

In [12]:
torch.where(b>0, b, 0)

tensor([1, 2, 3, 0, 0])

In [15]:
torch.exp(b)/ torch.sum(torch.exp(b))

tensor([0.0861, 0.2341, 0.6364, 0.0317, 0.0117])

In [16]:
b - torch.max(b)

tensor([-2, -1,  0, -3, -4])

In [18]:
x_max = torch.max(b)
x_exp = torch.exp(b - x_max)

# Compute the sum of the exponentials across all elements
x_exp_sum = torch.sum(x_exp)

# Normalize each row
softmax = x_exp / x_exp_sum

In [19]:
softmax

tensor([0.0861, 0.2341, 0.6364, 0.0317, 0.0117])

In [20]:
x_ = b - torch.max(b)
torch.exp(x_)/ torch.sum(torch.exp(x_))

tensor([0.0861, 0.2341, 0.6364, 0.0317, 0.0117])